from fpdf import FPDF

def generate_pdf(team_info, output_path):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, 'Wzór raportu z konkurencji "Inspekcja"', ln=True, align='C')
    pdf.ln(10)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, '1. Podstawowe informacje o wykonanej misji', ln=True)
    pdf.ln(5)
    # Tabela sekcja 1
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(60, 8, 'Nazwa / email', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(80, 8, f"{team_info['name']} / {team_info['email']}", 1)
    pdf.ln()
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(60, 8, 'Czas trwania lotu', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(80, 8, team_info['flight_time'], 1)
    pdf.ln()
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(60, 8, 'Data i godzina rozpoczęcia misji', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(80, 8, team_info['mission_start'], 1)
    pdf.ln()
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(60, 8, 'Data i godzina zakończenia misji', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(80, 8, team_info['mission_end'], 1)
    pdf.ln(15)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, '2. Dodatkowe informacje o wykonanej misji', ln=True)
    pdf.ln(5)
    # Tabela sekcja 2 (przykładowe dane)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(60, 8, 'Stan baterii przed wykonaniem lotu', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(80, 8, team_info.get('battery_before', '---'), 1)
    pdf.ln()
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(60, 8, 'Stan baterii po zakończeniu lotu', 1)
    pdf.set_font('Arial', '', 10)
    pdf.cell(80, 8, team_info.get('battery_after', '---'), 1)
    pdf.ln()
    pdf.output(output_path) 